#preload=/home/Jogeir/hdd/Pictures/after-sunset-minimal-4k-zm-2560x1440.jpg
#wallpaper=DP-1,/home/Jogeir/hdd/Pictures/after-sunset-minimal-4k-zm-2560x1440.jpg
#wallpaper=HDMI-A-1,/home/Jogeir/hdd/Pictures/after-sunset-minimal-4k-zm-2560x1440.jpg
#wallpaper=DP-2,/home/Jogeir/hdd/Pictures/after-sunset-minimal-4k-zm-2560x1440.jpg

wallpaper {
    monitor = DP-1
    path = /home/Jogeir/hdd/Pictures/
    fit_mode = cover
    order = random
  }

splash = false
