# =======================================================================================
# SCREENCONFIGURATIONS (conf/screen.conf)
# =======================================================================================

# Small screen (HDMI-A-1)
monitor = HDMI-A-1, 1920x1080@60, 0x730, 1

# Mainscreen 2560x1440 240hz (DP-1)
monitorv2 {
    output = DP-1
    mode = 2560x1440@240
    position = 1920x560
    scale = 1
    bitdepth = 10
    cm = hdr # hdr/srgb
    icc = /usr/share/color/icc/XG27AQDMG_custom.icc
    sdrbrightness = 3
    sdrsaturation = 1.4 
}

# Vertical screen (DP-2)
monitor = DP-2, 2560x1440@160, 4480x0, 1
monitor = DP-2, transform, 3

# Enable variable refresh rate (G-Sync) only for fullscreen windows to stabilize flickering
misc {
    vrr = 0
}
